# Numpy 

## Basics

In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
arr[0]

np.int64(1)

In [4]:
arr = np.array([[1,2], [3,4], [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
arr.ndim

2

In [5]:
arr.itemsize

8

In [10]:
arr.shape

(3, 2)

In [11]:
arr = np.array([[1,2], [3,4], [5,6]],
                dtype=np.float64)
arr

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [5]:
arr = np.zeros([2,5])
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
arr = np.ones([4,4])
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
arr.ndim

1

In [8]:
arr.shape

(10,)

In [9]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
print(arr.shape)

[1 2 3 4 5]
1
(5,)


## String Functions

In [21]:
arr1 = np.array(["Hello", "Hi"])
arr2 = np.array(["abc", "xyz"])

In [22]:
arrstring = np.char.add(arr1, arr2)
arrstring

array(['Helloabc', 'Hixyz'], dtype='<U8')

In [23]:
arr1 = np.array(["Hello"])
arr2 = np.array([3])

In [24]:
arrstring = np.char.multiply(arr1, arr2)
arrstring

array(['HelloHelloHello'], dtype='<U15')

In [25]:
arr = np.array(["Hello"])

In [27]:
arr = np.char.lower(arr)
arr

array(['hello'], dtype='<U5')

In [28]:
arr = np.char.upper(arr)
arr

array(['HELLO'], dtype='<U5')

In [29]:
namearray = np.array(["Elizer Ponio Jr"])

In [30]:
arr = np.char.split(namearray)
arr

array([list(['Elizer', 'Ponio', 'Jr'])], dtype=object)

## Array Manipulation

In [31]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
arr.shape

(9,)

In [40]:
arr2 = arr.reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
arr = np.arange(8)
#arr2 = arr.reshape(1,8)
# print(arr2)
#arr2 = arr.reshape(2,4)
# print(arr2)
arr2 = arr.reshape(2,2,2)
print(arr2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [13]:
arr2[0][0][0]

np.int64(0)

In [49]:
arr = np.arange(8)
arr = arr.reshape(4,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [51]:
arr3 = arr2.flatten()
arr3

array([0, 1, 2, 3, 4, 5, 6, 7])

In [52]:
arr3.ndim

1

In [53]:
arr3.shape

(8,)

In [14]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
transposedarr = np.transpose(arr)
transposedarr

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [50]:
arr = np.arange(8).reshape(2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [51]:
arr2 = arr.reshape(2,2,2)
arr2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [52]:
np.swapaxes(arr2, 1, 2)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

## Arithmetic Operations

In [17]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
b = np.array([10,20,10])
c = np.add(a,b)
print(c)

[[10 21 12]
 [13 24 15]
 [16 27 18]]


In [19]:
c = np.subtract(a,b)
print(c)

[[-10 -19  -8]
 [ -7 -16  -5]
 [ -4 -13  -2]]


In [20]:
c = np.multiply(a,b)
print(c)

[[  0  20  20]
 [ 30  80  50]
 [ 60 140  80]]


In [21]:
c = np.divide(a,b)
print(c)

[[0.   0.05 0.2 ]
 [0.3  0.2  0.5 ]
 [0.6  0.35 0.8 ]]


## Other functions

In [63]:
a = np.linspace(1, 3, 10)
a

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [23]:
a = np.array([(1,2,3), (3,4,5)])
print(a.sum(axis=1))

[ 6 12]


In [66]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [66]:
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]


In [67]:
print(np.std(a))

1.2909944487358056
