# Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

## where() function

#### Find the indexes where the value is 4:

In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


The example above will return a tuple: (array([3, 5, 6],)

Which means that the value 4 is present at index 3, 5, and 6.

#### Find the indexes where the values are even

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


#### Find the indexes where the values are odd

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


## searchsorted() function

searchsorted() performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

#### Find the indexes where the value 7 should be inserted:

In [34]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


#### Find the indexes where the values 2, 4, and 6 should be inserted:

In [35]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]
