In [418]:
import numpy as np

In [419]:
A = np.random.randint(1,10,size = (3,3))
B = np.random.randint(1,10,size = (3,2))

In [420]:
A

array([[7, 3, 9],
       [2, 6, 7],
       [3, 3, 5]])

In [421]:
B

array([[3, 2],
       [1, 5],
       [6, 7]])

In [422]:
c = A@B
c

array([[78, 92],
       [54, 83],
       [42, 56]])

In [423]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]

np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [424]:
A = np.random.randint(1,10,size = (3,3))
B = np.random.randint(1,10,size = (3,2))

np.dot(A,B)

array([[33, 93],
       [40, 96],
       [39, 99]])

In [425]:
c = np.array(a)@np.array(b)
c

array([[4, 1],
       [2, 2]])

In [426]:
a = np.array([[1,1,1], [1,2,3]])
b = np.array([[1, 1], [1, 2], [1, 3]])

result = a@b
result

array([[ 3,  6],
       [ 6, 14]])

In [427]:
a = np.array([[1, 1, 1], [1, 2, 3]])
b = np.array([[1], [3], [2]])

result = a@b
result


array([[ 6],
       [13]])

In [428]:
a = np.array([[3, 6], [6, 14]])
b = np.array([[1], [.5]])

result = a@b
result


array([[ 6.],
       [13.]])

In [429]:
a = (3 * 1) + (6 * .5)
b = (6 * 1) + (14 * .5)

print(a)
print(b)

6.0
13.0


In [430]:
b = 1
m = 0.5
x = 2

z = (m * x) + b 
z

2.0

In [431]:
X = [[3,6], [6,14]]

print(np.linalg.pinv(X))s
# y = [6, 13]
# print(np.dot(np.linalg.pinv(X),y))


[[ 2.33333333 -1.        ]
 [-1.          0.5       ]]


In [432]:
a = np.array([[1,1,1], [1,2,3]])
b = np.array([[1, 1], [1, 2], [1, 3]])

print(a@b)


[[ 3  6]
 [ 6 14]]
