# Copy and View

## Copy


In [8]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = arr1.copy()
arr1[0] = 42

print(arr1) 
print(arr2)

[42  2  3  4  5]
[1 2 3 4 5]


## View

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [9]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = arr1.view()
arr1[0] = 42

print(arr1) 
print(arr2)

[42  2  3  4  5]
[42  2  3  4  5]
