# Generate Random Number

#### Generate random int

In [43]:
from numpy import random

x = random.randint(100)

print(x)

50


#### Generate random float

In [44]:
x = random.rand()

print(x)

0.2943716845346377


## Random Distribution

Data Distribution is a list of all possible values, and how often each value occurs.

#### Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0



#### The choice() method allows us to specify the probability for each value.

In [45]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[5 7 5 5 5 5 5 7 5 5 7 5 7 5 5 7 7 7 7 5 7 7 5 3 3 5 3 5 7 5 7 7 7 7 5 5 7
 5 5 5 5 5 5 7 7 7 5 5 7 7 7 7 5 7 7 7 5 7 5 7 5 7 7 7 5 5 5 3 7 7 5 7 5 3
 7 5 7 3 7 5 7 7 7 3 7 7 3 5 7 7 5 7 7 7 3 7 5 5 7 7]


#### Same example as above, but return a 2-D array with 3 rows, each containing 5 values.

In [46]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[3 7 5 3 5]
 [7 7 7 7 7]
 [5 3 5 7 7]]


## Random Permutations
A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

#### Randomly shuffle elements of following array:

The shuffle() method makes changes to the original array.

In [47]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[5 2 3 1 4]


#### Generate a random permutation of elements of following array:

The permutation() method returns a re-arranged array (and leaves the original array un-changed).

In [48]:
arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))
print(arr)

[2 3 5 4 1]
[1 2 3 4 5]
