# Array Slicing 

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: **[start:end]**.

We can also define the step, like this: **[start:end:step]**.

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

#### Slice elements from index 1 to index 5 from the following array:

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


#### Slice elements from index 4 to the end of the array:

In [22]:
print(arr[4:])

[5 6 7]


#### Slice elements from the beginning to index 4 (not included):

In [23]:
print(arr[:4])

[1 2 3 4]


## Negative Slicing
Use the minus operator to refer to an index from the end:

In [24]:
print(arr)
print(arr[-3:-1])

[1 2 3 4 5 6 7]
[5 6]


## Step
Use the step value to determine the step of the slicing:

In [25]:
print(arr)

[1 2 3 4 5 6 7]


#### Return every other element from index 1 to index 5:

In [26]:
print(arr[1:5:2])

[2 4]


#### Return every other element from the entire array:

In [27]:
print(arr[::2])

[1 3 5 7]


## Slicing 2-D Arrays

#### From the second element, slice elements from index 1 to index 4 (not included):

In [28]:
arr2D = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr2D[1, 1:4])

[7 8 9]


#### From both elements, return index 2:

In [29]:
print(arr2D[0:2, 2])

[3 8]


##### From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [30]:
print(arr2D)
print("----")
print(arr2D[0:2, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
----
[[2 3 4]
 [7 8 9]]
